### ISSUE TITLE
problem with $ read-schema-org

### ISSUE THREAD

**Issue by mansoureh** [indexzero/node-schema-org#3]
Hi, thanks for the code! I have a problem with this module: when I run it , the last line it is shown in the console is:
" info:   Spawning: node /var/lib/stickshift/6c8414a379dd4f2d903646bfad80fd52/app-root/data/377879/node_modules/schema-org/bin/parse-schema --type ClothingStore --no-verbose"

seems never passes this part and after that my workplace is trapped in an endless waiting! do u have any idea about this issue?

**Comment by indexzero** [comment]
Dont bother attempt to parse the schema again. All parsed schemas are stored in `/schemas/*` so you can just require the stored JSON.

``` js
  var ClothingStore = require('schema-org/schemas/clothingstore');
```
